version: "3.5"

services:
  prez:
    image: prez:latest
    command: /bin/bash /start.sh ${theme}
    ports: 
      - ${port:-9000}:9000
    volumes:
      - ./:/opt/prez
      - ./start.sh:/start.sh
